[build-system]
requires = [
    "setuptools", 
    "numpy", 
    "scipy",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "mlmodel: marks tests as machine learning models (deselect with '-m \"not mlmodel\"')",
]
